on:
  schedule:
    - cron:  '0 0 1 * *'

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - mode: 1
            language: ngerman
            artifact: DE_DOC_LatexVorlage
          - mode: 3
            language: ngerman
            artifact: DE_SUMMARY_LatexVorlage
          - mode: 5
            language: ngerman
            artifact: DE_PRESENTATION_LatexVorlage
          - mode: 9
            language: ngerman
            artifact: DE_PAPER_LatexVorlage
          - mode: 2
            language: ngerman
            artifact: DE_LatexVorlage
          - mode: 2
            language: english
            artifact: EN_LatexVorlage
          - mode: 2
            language: ngerman
            titlepage: fhv
            artifact: DE_LatexVorlage-fhv
          - mode: 2
            language: english
            titlepage: fhv
            artifact: EN_LatexVorlage-fhv
    steps:
    - uses: actions/checkout@v6
    - name: Build FHVMODE=${{ matrix.mode }} ${{ matrix.language }} ${{ matrix.titlepage }}
      run: |
        make clean
        make FHVMODE=${{ matrix.mode }} LANGUAGE=${{ matrix.language }} ${{ matrix.titlepage && format('FHVTITLEPAGE={0}', matrix.titlepage) || '' }}
        cp build/LatexVorlage.pdf build/${{ matrix.artifact }}.pdf
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ matrix.artifact }}
        path: build/${{ matrix.artifact }}.pdf
